[package]
name = "program_synthesis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdext = "0.3.2"
rand = "0.9.0-alpha.1"
strum = "0.17.1"
strum_macros = "0.17.1"
